### ISSUE TITLE
🐛-创建管连接界面卡死

### ISSUE THREAD

**Issue by WanShufen** [undb-xyz/undb#1046]
### Description

创建一个表的时候同时创建关联列，关联列选择关联表，前端报错，如图

<img width="1438" alt="image" src="https://github.com/undb-xyz/undb/assets/73324423/2580334e-4022-4683-bb97-891090303944">

### Reproduction steps

```bash
1. 点击创建新表
2. 添加reference列
3. 为关联列选择关联表
4. console error： Cannot read properties of undefined (reading 'id')
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Chrome

**Comment by nichenqin** [comment]
无法复现呢
