### ISSUE TITLE
How many records per table is recommended? 

### ISSUE THREAD

**Issue by happy15** [undb-xyz/undb#1219]
Airtable has a limitation of 100k records per table in their business version. So I am wondering  how many records per table is recommended in undb?

**Comment by nichenqin** [comment]
100k is ok for undb now. In future we will implement pagination so the answer may be infinite 😀

**Comment by happy15** [comment]
I noticed that this project has tag of sqlite3 and there is dependency to sqlite3 and mongodb in backend, a quick guess is that undb relies on existed database rather than building one, am I right?

**Comment by nichenqin** [comment]
> I noticed that this project has tag of sqlite3 and there is dependency to sqlite3 and mongodb in backend, a quick guess is that undb relies on existed database rather than building one, am I right?

undb is built on top of sqlite3, mongodb is used as internal cache layer prodiver optional(maybe our document is a little bit confuse and we will edit later). undb does not rely on any existing db and the data should controlled by undb

**Comment by nichenqin** [comment]
undb only requires`sqlite` to work by default, any other dependency like `redis` `mongo` or `temporal` are optional just for better deployment

**Comment by happy15** [comment]
Good to know.

Sorry for the confusion by "relies on existed database". What I mean is "depends on existing database software like sqlite3".

Thanks for your explanation and hope everything goes well. 👏
