### ISSUE TITLE
[feature]: correct "widget" spelling

### ISSUE THREAD

**Issue by octoshrimpy** [undb-xyz/undb#1222]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Is the misspelling on purpose? it's everywhere.
![image](https://github.com/undb-xyz/undb/assets/7097172/9470b142-3bcd-49cd-b7a8-a3c1a5b2e88d)

I can make a PR to fix this, if wanted.

### Why should this be worked on?

see above

**Comment by nichenqin** [comment]
thank you , it looks like may affect database schema, so I'll try to fix it as soon as possible
