### ISSUE TITLE
🐛 [BUG] - dashboard: `number>min` widget not grabbing proper value

### ISSUE THREAD

**Issue by octoshrimpy** [undb-xyz/undb#1226]
### Description

![image](https://github.com/undb-xyz/undb/assets/7097172/d2efa3d1-30bf-46a4-8a8b-54631c5c58e3)

It defaults to 0, when there is not anything smaller than 100 in the table: 

![image](https://github.com/undb-xyz/undb/assets/7097172/45dcd007-5cb8-421f-b6d3-5b6c771dfbac)

### Browsers

Firefox, Chrome

**Comment by nichenqin** [comment]
I cannot reproduce it now, will try it later. cc @WanShufen
