### ISSUE TITLE
🐛 [BUG] - Live demo is not working

### ISSUE THREAD

**Issue by 51750** [undb-xyz/undb#1308]
### Description

Live demo is not working

### Reproduction URL

https://demo.undb.xyz/login?redirectTo=/

### Reproduction steps

```bash
1. Open the Live demo page.
2. Click on Login button.
3. Waiting a moment.
4. Alert "Error".
```

### Screenshots

<img width="1298" alt="2023-07-08 16 49 32" src="https://github.com/undb-xyz/undb/assets/4531076/2000f0a9-0efb-4ecd-83c6-1e41398d755f">

### Logs

```bash
Failed to load resource: the server responded with a status of 500 ()
start.2a137bf8.js:1     POST https://demo.undb.xyz/api/auth/login 500

{
    "message": "Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?",
    "statusCode": 500,
    "timestamp": "2023-07-08T08:50:43.121Z",
    "path": "/api/auth/login"
}
```

### Browsers

Chrome

**Comment by nichenqin** [comment]
Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call

**Comment by nichenqin** [comment]
maybe there is a dead transaction
