### ISSUE TITLE
🐛 [BUG] - dropdowns scroll too far

### ISSUE THREAD

**Issue by octoshrimpy** [undb-xyz/undb#1312]
### Description

![image](https://github.com/undb-xyz/undb/assets/7097172/48cc1291-8e30-4d0c-bd3a-108d4ac16c34)

triggered on cell type, but I believe it's almost everywhere that the custom dropdown is used.

### Reproduction steps

```bash
.
```

**Comment by nichenqin** [comment]
looks like fixed in flowbite 0.40
