### ISSUE TITLE
🐛 [BUG] - cannot import csv, cannot exit modal

### ISSUE THREAD

**Issue by octoshrimpy** [undb-xyz/undb#1314]
### Description

upon drag-drop, or click and upload, this error fires. After that, neither the cancel button or the [ X ] top-right are able to close the modal. user needs to refresh page to get back to app.

![image](https://github.com/undb-xyz/undb/assets/7097172/99541c6c-c00b-43ce-9717-aa11508bf50f)

latest docker version as the time this was created. 

### Reproduction steps

```bash
1. Go to 'upload csv, excel, json'
2. drag file in over modal
3. open console
4. See error
```

**Comment by nichenqin** [comment]
@octoshrimpy can you upload your csv file?
