### ISSUE TITLE
[feature]: app version shown in settings

### ISSUE THREAD

**Issue by octoshrimpy** [undb-xyz/undb#1315]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

will make it easier to debug and check if issues coming in are from an older version of the app where they may have been fixed.

### Why should this be worked on?

easier to troubleshoot.

**Comment by nichenqin** [comment]
<img width="1053" alt="image" src="https://github.com/undb-xyz/undb/assets/22788984/41313aa3-42a4-4ce3-89b2-81ec736b6ace">
