### ISSUE TITLE
🐛 [BUG] - min field should not display required toggle

### ISSUE THREAD

**Issue by WanShufen** [undb-xyz/undb#1319]
### Description

 <img width="1439" alt="image" src="https://github.com/undb-xyz/undb/assets/73324423/4e7ee39f-482f-4a92-a3a9-c84c8d253a33">

### Reproduction steps

```bash
1. Create New Table
2. Create a column of reference type and reference another table
```

**Comment by wingkwong** [comment]
I didn't see this required button.

![image](https://github.com/undb-xyz/undb/assets/35857179/13988f4d-998d-4064-b3ad-4a9b4bc7ac2a)

**Comment by wingkwong** [comment]
Ok I got the problem. It's from update form and It doesn't relate to min field specifically. Will create a new PR soon.
