### ISSUE TITLE
🐛 创建一个新列失败接口报错并且交互流程建议修改

### ISSUE THREAD

**Issue by WanShufen** [undb-xyz/undb#1481]
### Description

1. 创建列接口报错信息：

[
    {
        "error": {
            "message": "An open transaction is required for this operation",
            "code": -32603,
            "data": {
                "code": "INTERNAL_SERVER_ERROR",
                "httpStatus": 500,
                "stack": "ValidationError: An open transaction is required for this operation\n    at ValidationError.transactionRequired (/Users/sophie/undb/node_modules/.pnpm/@mikro-orm+core@5.7.14_@mikro-orm+better-sqlite@5.7.14_@mikro-orm+migrations@5.7.14/node_modules/@mikro-orm/core/errors.js:37:16)\n    at SqlEntityManager.rollback (/Users/sophie/undb/node_modules/.pnpm/@mikro-orm+core@5.7.14_@mikro-orm+better-sqlite@5.7.14_@mikro-orm+migrations@5.7.14/node_modules/@mikro-orm/core/EntityManager.js:720:44)\n    at NestSqliteUnitOfWork.rollback (file:///Users/sophie/undb/packages/database/sqlite/dist/sqlite.uow.js:20:20)\n    at NestSqliteUnitOfWork.rollback (file:///Users/sophie/undb/apps/backend/dist/uow/uow.service.js:27:21)\n    at /Users/sophie/undb/node_modules/.pnpm/@mikro-orm+core@5.7.14_@mikro-orm+better-sqlite@5.7.14_@mikro-orm+migrations@5.7.14/node_modules/@mikro-orm/core/decorators/UseRequestContext.js:16:39\n    at AsyncLocalStorage.run (node:async_hooks:346:14)\n    at RequestContext.createAsync (/Users/sophie/undb/node_modules/.pnpm/@mikro-orm+core@5.7.14_@mikro-orm+better-sqlite@5.7.14_@mikro-orm+migrations@5.7.14/node_modules/@mikro-orm/core/utils/RequestContext.js:32:29)\n    at descriptor.value (/Users/sophie/undb/node_modules/.pnpm/@mikro-orm+core@5.7.14_@mikro-orm+better-sqlite@5.7.14_@mikro-orm+migrations@5.7.14/node_modules/@mikro-orm/core/decorators/UseRequestContext.js:15:58)\n    at CreateFieldCommandHandler.execute (file:///Users/sophie/undb/packages/cqrs/dist/index.js:1:2534)\n    at runNextTicks (node:internal/process/task_queues:60:5)",
                "path": "table.field.create"
            }
        }
    }
]

2. 订阅接口会比创建列接口先返回

![image](https://github.com/undb-xyz/undb/assets/73324423/d7d92a35-d6b5-43cd-b82b-76df9360e037)

3.  视频中可见创建列之后弹窗信息会自动清空，用户无感知是已经发送了接口，会以为是个bug（视频有点长）建议接口请求过程中添加一个Overlay罩住弹窗不能让用户继续操作

https://github.com/undb-xyz/undb/assets/73324423/45fe0dc9-70d5-4198-8057-3a594e4e7e0b

### Reproduction steps

```bash
1. 打开一张表
2. 点击创建列
3. 输入列名
4. 点击创建

在 shadcn-svelte 分支上测试的

问题一共有三点在上面描述中已经列出
```

**Comment by nichenqin** [comment]
在分支修改好了
