### ISSUE TITLE
🐛 [BUG] - Uploading big file to demo server crashed it

### ISSUE THREAD

**Issue by geekyayush** [undb-xyz/undb#1653]
### Description

When I try to import a big file e.g. 10k+ records, after sometime, the demo server crashes and shows 502.

URL: https://demo.[undb](https://demo.undb.xyz/).xyz/

![image](https://github.com/undb-xyz/undb/assets/25874080/d6dca29b-efd8-4d55-be8a-83c99108b019)

### Reproduction URL

https://demo.undb.xyz/

### Reproduction steps

```bash
1. Go to 'https://demo.undb.xyz/'
2. Click on 'import option'
3. Upload a file with 10k+ records.
4. See error after timeout
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by nichenqin** [comment]
The demo website I'm using has a very low server configuration, so some batch operations might cause it to crash. If possible, you could try creating a UNDB instance locally for testing.
