### ISSUE TITLE
Failed to create a tree-type column.

### ISSUE THREAD

**Issue by WanShufen** [undb-xyz/undb#869]
https://user-images.githubusercontent.com/73324423/231958695-64506147-e02e-45fc-be90-4d83c35a1568.mov

![image](https://user-images.githubusercontent.com/73324423/231958834-12a9722a-935f-422e-b965-0f2862dd9e6b.png)
![image](https://user-images.githubusercontent.com/73324423/231959061-d4b969c6-5e5a-42f1-9da5-986ec2dc1ff0.png)

**Comment by Sophie4140** [comment]
现在好像是正常了
