### ISSUE TITLE
There is a bug in the maximum value for creating a rating column

### ISSUE THREAD

**Issue by WanShufen** [undb-xyz/undb#871]
![image](https://user-images.githubusercontent.com/73324423/231963224-410f019b-e4be-47b6-982a-e48ef6674e76.png)

**Comment by nichenqin** [comment]
你这个不对吧，不就是把最大值从 5 改成 9 吗？这为啥不行呢？

**Comment by WanShufen** [comment]
rating字段有最大值限制吗？我看好像没有，没有的话 我设置为9为啥不能被设置成功呢？

**Comment by WanShufen** [comment]
https://user-images.githubusercontent.com/73324423/232194427-ff0baad3-46bb-47c9-82ea-ae7987753241.mov
