### ISSUE TITLE
Reference Column issue 

### ISSUE THREAD

**Issue by WanShufen** [undb-xyz/undb#876]
https://user-images.githubusercontent.com/73324423/231983876-9ecc0f32-664c-40ee-a1e3-94d169cceeaf.mov
两个问题：
1、上述视屏的中的问题；
2、多表关联需confirm按钮无法点击，如下图；
![image](https://user-images.githubusercontent.com/73324423/231987081-cf0922b9-0598-4283-9eae-8027aa5a2a4b.png)

**Comment by Sophie4140** [comment]
目前develop分之上测试还是没有好
