### ISSUE TITLE
The deletion table interface request has been in a "padding" state, resulting in a frozen and unresponsive interface.

### ISSUE THREAD

**Issue by WanShufen** [undb-xyz/undb#932]
删除表格时间有点过长了，一分多钟，界面一直卡死状态
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/73324423/236629307-ab39d63f-2b0c-4259-8db9-d6800075b339.png">
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/73324423/236629410-df90d4e5-b38f-45ce-85fc-0e64d38b6527.png">

**Comment by nichenqin** [comment]
加了个禁用的状态和 loading spinner 速度的问题我升级了机器了可以再看看
