### ISSUE TITLE
创建关联列的时候，选择显示列应该为必填操作，没有填写时完成按钮和创建按钮都应该置灰

### ISSUE THREAD

**Issue by WanShufen** [undb-xyz/undb#961]
如果第一次创建关联列的时候在未填写显示列的情况下点击了完成，关联列信息自动被清空了，如果再次添加新列，并正确填写也无法成功创建表，如图二
<img width="1004" alt="image" src="https://github.com/undb-xyz/undb/assets/73324423/9f0e48bd-ac96-47dc-af3a-6137bbe28fc6">
其实只有两个列，第二个列信息就是最开始没有填写显示列的关联列信息，但是用户无法将之前未选择的显示列填写，导致接口传参数组中有三个，其实只是想要创建两个列信息，一个name 一个Reference
<img width="1417" alt="image" src="https://github.com/undb-xyz/undb/assets/73324423/c968467a-24d5-4688-90ff-f9f749feb9a5">

传参：
{
    "0": {
        "schema": [
            {
                "id": "fldcjtygbey",
                "type": "string",
                "name": "name",
                "display": true,
                "description": "",
                "required": false
            },
            {
                "id": "fldfbu5r516",
                "type": "reference",
                "name": "Reference",
                "display": false,
                "description": "",
                "required": false,
                "foreignTableId": "tblowel5rd0",
                "displayFieldIds": [],
                "bidirectional": false
            },
            {
                "id": "fldtm6dsrvl",
                "type": "reference",
                "name": "Reference",
                "display": false,
                "description": "",
                "required": false,
                "options": [
                    {
                        "name": "",
                        "color": {
                            "name": "indigo",
                            "shade": 5
                        }
                    }
                ],
                "foreignTableId": "tblowel5rd0",
                "displayFieldIds": [
                    "fldr3h3oi2v"
                ],
                "bidirectional": false
            }
        ],
        "name": "test1"
    }
}

**Comment by nichenqin** [comment]
@WanShufen 这个看了几遍我表示看不懂
