### ISSUE TITLE
删除表中的关联列，界面数据会报错

### ISSUE THREAD

**Issue by WanShufen** [undb-xyz/undb#962]
如视频现象
解决方案：
1、在关联列被删除之后，其余与关联列相关的列也默认被删除，并且在删除的时候弹出二次确认弹窗提示用户
2、在有与关联列相关的其他列存在时，关联列不允许被删除。并有用户提示信息
https://github.com/undb-xyz/undb/assets/73324423/439f3024-853c-4f39-a28c-311ff330a304

**Comment by nichenqin** [comment]
现在会显示一个红色的感叹号

**Comment by WanShufen** [comment]
已验收
