### ISSUE TITLE
筛选功能故障

### ISSUE THREAD

**Issue by WanShufen** [undb-xyz/undb#964]
第一个视频中有两个问题：
1、在筛选条件列类型为数值类型，筛选条件默认为0 时，点击应用筛选条件没有被创建成功
2、筛选条件创建成功后，界面数据没有按照筛选条件正确展示（其实这个就是界面没有自动刷新重新拉数据）

https://github.com/undb-xyz/undb/assets/73324423/bcdba98c-5f65-4941-b658-56c0ad883401

第二个视频中有一个问题：
筛选条件生效，界面卡死，接口请求正确，筛选条件弹窗也无法关闭

https://github.com/undb-xyz/undb/assets/73324423/14ee6cec-4e22-4608-910c-6e811e336a5a

第三个视频里有一个问题：
创建的筛选条件是选择创建时间，选择的创建时间为今日，数据也是今日创建的，但是刷新界面后数据显示为空，接口返回就为空，后端问题

https://github.com/undb-xyz/undb/assets/73324423/6820368e-0ad2-48b6-b932-bf9c5fb53301

**Comment by nichenqin** [comment]
第三个问题你选的是个绝对时间，要每分每秒都要一样，后面 date 会加显示时间，如果你要选今天，那就要在中间的选项中选「是今天」

**Comment by nichenqin** [comment]
不是，是中间那个，选是今天 ，不是最右边选今天，你理解下什么区别吧
