### ISSUE TITLE
关联表多选之后无法删除已有的选项

### ISSUE THREAD

**Issue by WanShufen** [undb-xyz/undb#972]
行为如下视频

https://github.com/undb-xyz/undb/assets/73324423/75490982-e2c7-4e0c-bcc8-1efbdd0d0ec3

看起来是前端Bug 

<img width="1215" alt="image" src="https://github.com/undb-xyz/undb/assets/73324423/ed997ff1-8fb1-47cd-8c7d-9d54b18e41f2">

**Comment by nichenqin** [comment]
你没点更新吧
